// SPDX-License-Identifier: MIT OR Apache-2.0
// Original Semwright architecture. Uses the unmodified system libfaust API.
// This executable is owner-pinned and invoked by Driver Host, never by a shell.
#include <faust/dsp/interpreter-dsp.h>
#include <sndfile.h>
#include <algorithm>
#include <array>
#include <charconv>
#include <cmath>
#include <cstdint>
#include <fcntl.h>
#include <iostream>
#include <memory>
#include <stdexcept>
#include <string>
#include <sys/stat.h>
#include <unistd.h>
#include <vector>

namespace {
constexpr std::size_t max_source = 60000;
constexpr int block_frames = 1024;
constexpr std::uint64_t max_frames = 96000ULL * 600ULL;
std::uint64_t integer(const char* value, std::uint64_t low, std::uint64_t high) {
    std::string text(value);
    std::uint64_t result = 0;
    auto parsed = std::from_chars(text.data(), text.data() + text.size(), result);
    if (parsed.ec != std::errc() || parsed.ptr != text.data() + text.size()
        || result < low || result > high) throw std::runtime_error("invalid bounded integer");
    return result;
}
std::string read_source() {
    std::string source;
    std::array<char, 4096> buffer{};
    while (std::cin) {
        std::cin.read(buffer.data(), buffer.size());
        source.append(buffer.data(), static_cast<std::size_t>(std::cin.gcount()));
        if (source.size() > max_source) throw std::runtime_error("source exceeds sealed-tool limit");
    }
    if (source.empty() || source.find('\0') != std::string::npos)
        throw std::runtime_error("invalid source bytes");
    // Input is generated by the trusted Rust translator. These checks also close
    // external file/foreign-code mechanisms if the helper is invoked incorrectly.
    for (const auto* forbidden : {"ffunction", "fvariable", "fconstant", "component(",
                                  "library(", "soundfile(", "http:", "https:", "file:"})
        if (source.find(forbidden) != std::string::npos)
            throw std::runtime_error("external Faust mechanism is forbidden");
    const std::string allowed = "import(\"stdfaust.lib\");";
    if (source.compare(0, allowed.size(), allowed) != 0
        || source.find("import", allowed.size()) != std::string::npos)
        throw std::runtime_error("only the fixed standard library import is accepted");
    return source;
}
struct FactoryDelete {
    void operator()(interpreter_dsp_factory* factory) const {
        if (factory) deleteInterpreterDSPFactory(factory);
    }
};
using Factory = std::unique_ptr<interpreter_dsp_factory, FactoryDelete>;
struct FileDelete { void operator()(SNDFILE* file) const { if (file) sf_close(file); } };
using SoundFile = std::unique_ptr<SNDFILE, FileDelete>;
std::string safe_version() {
    std::string version(getCLibFaustVersion());
    if (version.size() > 128) throw std::runtime_error("invalid library version");
    for (char c : version) if (!(std::isalnum(static_cast<unsigned char>(c)) || c == '.' || c == '-' || c == ' '))
        throw std::runtime_error("unexpected library version characters");
    return version;
}
int execute(int argc, char** argv) {
    if (argc == 2 && std::string(argv[1]) == "version") {
        std::cout << "{\"schema_version\":1,\"engine\":\"faust-interpreter\",\"compiler_version\":\""
                  << safe_version() << "\"}\n";
        return 0;
    }
    const bool validate = argc == 3 && std::string(argv[1]) == "validate";
    const bool render = argc == 8 && std::string(argv[1]) == "render";
    if (!validate && !render) throw std::runtime_error("unsupported fixed helper operation");
    const std::string libraries(argv[2]);
    if (libraries.empty() || libraries.front() != '/' || libraries.size() > 4096
        || libraries.find("..") != std::string::npos)
        throw std::runtime_error("invalid library mount");
    struct stat metadata{};
    if (lstat(libraries.c_str(), &metadata) || !S_ISDIR(metadata.st_mode))
        throw std::runtime_error("library mount is not a real directory");
    auto source = read_source();
    const char* options[] = {"-I", libraries.c_str(), "-single"};
    std::string error;
    Factory factory(createInterpreterDSPFactoryFromString("semwright-audio", source, 3, options, error));
    if (!factory) {
        // Diagnostics are bounded; no unbounded compiler output becomes protocol data.
        std::cerr << error.substr(0, 4096) << '\n';
        throw std::runtime_error("Faust interpreter compilation failed");
    }
    std::unique_ptr<interpreter_dsp> processor(factory->createDSPInstance());
    if (!processor || processor->getNumInputs() != 0)
        throw std::runtime_error("synthesis helper requires zero external inputs");
    const auto channels = processor->getNumOutputs();
    if (channels < 1 || channels > 16) throw std::runtime_error("DSP channel budget exceeded");
    if (validate) {
        std::cout << "{\"schema_version\":1,\"valid\":true,\"outputs\":" << channels
                  << ",\"compiler_version\":\"" << safe_version() << "\"}\n";
        return 0;
    }
    const std::string directory(argv[3]);
    const auto rate = integer(argv[4], 8000, 192000);
    const auto frames = integer(argv[5], 1, max_frames);
    const std::string format(argv[6]);
    const auto bits = integer(argv[7], 16, 32);
    if ((format != "wav" && format != "flac") || (bits != 16 && bits != 24 && bits != 32)
        || (format == "flac" && bits == 32)) throw std::runtime_error("unsupported output encoding");
    const int root = open(directory.c_str(), O_DIRECTORY | O_RDONLY | O_CLOEXEC | O_NOFOLLOW);
    if (root < 0) throw std::runtime_error("private output directory unavailable");
    const std::string name = "render." + format;
    const int fd = openat(root, name.c_str(), O_CREAT | O_EXCL | O_RDWR | O_CLOEXEC | O_NOFOLLOW, 0600);
    close(root);
    if (fd < 0) throw std::runtime_error("output must be a new regular file");
    SF_INFO info{};
    info.samplerate = static_cast<int>(rate);
    info.channels = channels;
    info.format = (format == "wav" ? SF_FORMAT_WAV : SF_FORMAT_FLAC)
                | (bits == 16 ? SF_FORMAT_PCM_16 : bits == 24 ? SF_FORMAT_PCM_24 : SF_FORMAT_PCM_32);
    SoundFile output(sf_open_fd(fd, SFM_WRITE, &info, SF_TRUE));
    if (!output) { close(fd); throw std::runtime_error("encoder initialization failed"); }
    // Integer conversion saturation is explicit. No true-peak or loudness guarantee.
    sf_command(output.get(), SFC_SET_CLIPPING, nullptr, SF_TRUE);
    processor->init(static_cast<int>(rate));
    std::vector<std::vector<FAUSTFLOAT>> buffers(channels, std::vector<FAUSTFLOAT>(block_frames));
    std::vector<FAUSTFLOAT*> pointers;
    for (auto& buffer : buffers) pointers.push_back(buffer.data());
    std::vector<float> interleaved(static_cast<std::size_t>(channels) * block_frames);
    std::uint64_t clipped = 0;
    for (std::uint64_t done = 0; done < frames;) {
        const auto count = static_cast<int>(std::min<std::uint64_t>(block_frames, frames - done));
        processor->compute(count, nullptr, pointers.data());
        for (int frame = 0; frame < count; ++frame) {
            for (int channel = 0; channel < channels; ++channel) {
                const auto sample = buffers[channel][frame];
                if (!std::isfinite(sample)) throw std::runtime_error("nonfinite DSP output");
                if (std::abs(sample) > 1) ++clipped;
                interleaved[static_cast<std::size_t>(frame) * channels + channel] = sample;
            }
        }
        if (sf_writef_float(output.get(), interleaved.data(), count) != count)
            throw std::runtime_error("short audio write");
        done += static_cast<std::uint64_t>(count);
    }
    sf_write_sync(output.get());
    if (sf_close(output.release()) != 0) throw std::runtime_error("audio finalization failed");
    std::cout << "{\"schema_version\":1,\"frames\":" << frames << ",\"sample_rate\":" << rate
              << ",\"channels\":" << channels << ",\"clipped_input_samples\":" << clipped
              << ",\"compiler_version\":\"" << safe_version()
              << "\",\"engine\":\"faust-interpreter\",\"dither\":\"none\"}\n";
    return 0;
}
}
int main(int argc, char** argv) {
    try { return execute(argc, argv); }
    catch (const std::exception& error) { std::cerr << error.what() << '\n'; return 1; }
}
