use super::*;
use serde_json::json;

pub(super) fn generate(spec: &GodotAuthoringSpec, scene: &Scene) -> Result<(String, String)> {
    let paths = super::super::validate::paths(scene)?;
    let b = &scene.behavior;
    let mut code = format!(
        "# Generated by {GENERATOR_VERSION}; edit the typed intent, not this managed file.\nextends \"res://scripts/_sw_runtime.gd\"\n"
    );
    for signal in &b.signals {
        code.push_str(&format!("signal sw_signal_{signal}()\n"));
    }
    for v in &b.variables {
        let t = match v.initial.value_type() {
            ValueType::Bool => "bool",
            ValueType::Int => "int",
            ValueType::Scalar => "float",
            ValueType::Vector2 => "Vector2",
            ValueType::Vector3 => "Vector3",
            ValueType::Color => "Color",
        };
        code.push_str(&format!("var v_{}: {t} = {}\n", v.id, value(&v.initial)));
    }
    for e in &scene.entities {
        code.push_str(&format!(
            "@onready var n_{}: {} = get_node_or_null({})\n",
            e.id,
            e.node.class(),
            quoted(&paths[&e.id])
        ));
    }
    for t in &b.timers {
        code.push_str(&format!(
            "@onready var t_{}: Timer = get_node_or_null({})\n",
            t.id,
            quoted(&format!("_sw_timer_{}", t.id))
        ));
    }
    let l = &spec.limits;
    code.push_str(&format!("\nfunc _init() -> void:\n    sw_state = {}\n    _sw_limits = {{\"event\": {}, \"tick\": {}, \"events\": {}, \"entities\": {}, \"spawns\": {}}}\n",quoted(&b.initial_state),l.actions_per_event,l.actions_per_tick,l.events_per_tick,l.entities,l.spawns_per_tick));
    code.push_str("\nfunc _ready() -> void:\n    if get_tree().get_node_count() > _sw_limits.entities:\n        _sw_fail(\"entity_budget\")\n        return\n");
    for e in &scene.entities {
        code.push_str(&format!("    if not _sw_binding(n_{}): return\n", e.id));
    }
    for (i, h) in b.handlers.iter().enumerate() {
        match &h.event {
            Event::AreaEntered { area, .. } => code.push_str(&format!(
                "    n_{area}.body_entered.connect(_sw_area_{i})\n"
            )),
            Event::Timer { timer } => {
                code.push_str(&format!("    t_{timer}.timeout.connect(_sw_h_{i})\n"))
            }
            Event::Signal { signal } => {
                code.push_str(&format!("    sw_signal_{signal}.connect(_sw_h_{i})\n"))
            }
            _ => {}
        }
    }
    for (i, h) in b.handlers.iter().enumerate() {
        if matches!(h.event, Event::Ready) {
            code.push_str(&format!("    _sw_h_{i}()\n"));
        }
    }
    code.push_str("\nfunc _physics_process(_delta: float) -> void:\n    if not _sw_spend(0): return\n    sw_ticks += 1\n    var queued: Array[String] = _sw_queue\n    _sw_queue = []\n    for signal_id in queued:\n        if not sw_fault.is_empty(): return\n");
    if b.signals.is_empty() {
        code.push_str("        pass\n");
    } else {
        code.push_str("        match signal_id:\n");
        for s in &b.signals {
            code.push_str(&format!(
                "            {}: sw_signal_{s}.emit()\n",
                quoted(s)
            ));
        }
    }
    for (i, h) in b.handlers.iter().enumerate() {
        if matches!(h.event, Event::PhysicsTick) {
            code.push_str(&format!("    _sw_h_{i}()\n"));
        }
    }
    for e in &scene.entities {
        match &e.node {
            NativeNode::Camera2d{follow}=>code.push_str(&format!("    if not _sw_binding(n_{0}) or not _sw_binding(n_{follow}): return\n    n_{0}.global_position = n_{follow}.global_position\n",e.id)),
            NativeNode::Camera3d{follow,offset,..}=>code.push_str(&format!("    if not _sw_binding(n_{0}) or not _sw_binding(n_{follow}): return\n    n_{0}.global_position = n_{follow}.global_position + {1}\n    if n_{0}.global_position.distance_squared_to(n_{follow}.global_position) > 0.000001:\n        n_{0}.look_at(n_{follow}.global_position, {2})\n",e.id,vector("Vector3",offset),if offset[0].abs()+offset[2].abs()<0.0001 {"Vector3.FORWARD"}else{"Vector3.UP"})),_=>{}
        }
    }
    code.push_str("\nfunc _unhandled_input(event: InputEvent) -> void:\n    if not sw_fault.is_empty() or event.is_echo(): return\n");
    for (i, h) in b.handlers.iter().enumerate() {
        if let Event::Input { action } = &h.event {
            code.push_str(&format!(
                "    if event.is_action_pressed({}): _sw_h_{i}()\n",
                quoted(action)
            ));
        }
    }
    for (i, h) in b.handlers.iter().enumerate() {
        if let Event::AreaEntered { body, .. } = &h.event {
            code.push_str(&format!(
                "\nfunc _sw_area_{i}(body: Node) -> void:\n    if body == n_{body}: _sw_h_{i}()\n"
            ));
        }
    }
    code.push_str(&expressions(b));
    let mut mappings = Vec::new();
    for (i, h) in b.handlers.iter().enumerate() {
        let start = code.lines().count() + 1;
        code.push_str(&format!(
            "\n# logical handler: {}\nfunc _sw_h_{i}() -> void:\n    if not _sw_begin(): return\n",
            h.id
        ));
        if let Some(state) = &h.state {
            code.push_str(&format!("    if sw_state != {}: return\n", quoted(state)));
        }
        code.push_str("    var e: Array = _sw_eval()\n    if not sw_fault.is_empty(): return\n");
        if let Some(guard) = h.condition {
            code.push_str(&format!("    if not e[{guard}]: return\n"));
        }
        code.push_str(&format!("    for _repeat in range({}):\n", h.repeat));
        for a in &h.actions {
            code.push_str("        if not _sw_step(): return\n        e = _sw_eval()\n        if not sw_fault.is_empty(): return\n");
            code.push_str(&action(a));
        }
        mappings.push(
            json!({"logical_handler":h.id,"start_line":start,"end_line":code.lines().count()}),
        );
    }
    let map = json!({"version":1,"generator":GENERATOR_VERSION,"scene":scene.id,"source_sha256":Digest::of_bytes(code.as_bytes()),"handlers":mappings});
    Ok((
        code,
        serde_json::to_string_pretty(&map).expect("source map serialization"),
    ))
}

fn expressions(b: &Behavior) -> String {
    let mut code = String::from("\nfunc _sw_eval() -> Array:\n    var e: Array = []\n");
    for expression in &b.expressions {
        let term = match expression {
            Expression::Literal { value: v } => value(v),
            Expression::Read { variable } => format!("v_{variable}"),
            Expression::Axis { negative, positive } => {
                format!("Input.get_axis({}, {})", quoted(negative), quoted(positive))
            }
            Expression::Not { operand } => format!("not e[{operand}]"),
            Expression::Vector2 { x, y } => format!("Vector2(e[{x}], e[{y}])"),
            Expression::Vector3 { x, y, z } => format!("Vector3(e[{x}], e[{y}], e[{z}])"),
            Expression::Clamp { value: v, min, max } => {
                code.push_str(&format!("    if e[{min}] > e[{max}]:\n        _sw_fail(\"inverted_clamp\")\n        return []\n"));
                format!("clamp(e[{v}], e[{min}], e[{max}])")
            }
            Expression::Binary { op, left, right } => {
                if *op == BinaryOp::Divide {
                    code.push_str(&format!("    if e[{right}] == 0:\n        _sw_fail(\"division_by_zero\")\n        return []\n"));
                }
                let optext = match op {
                    BinaryOp::Add => "+",
                    BinaryOp::Subtract => "-",
                    BinaryOp::Multiply => "*",
                    BinaryOp::Divide => "/",
                    BinaryOp::Less => "<",
                    BinaryOp::Equal => "==",
                    BinaryOp::And => "and",
                    BinaryOp::Or => "or",
                };
                if *op == BinaryOp::Divide {
                    format!("e[{left}] / float(e[{right}])")
                } else {
                    format!("e[{left}] {optext} e[{right}]")
                }
            }
        };
        code.push_str(&format!("    e.append({term})\n    if not _sw_valid(e.back()):\n        _sw_fail(\"numeric_range\")\n        return []\n"));
    }
    code.push_str("    return e\n");
    code
}
fn action(a: &Action) -> String {
    let binding = |id: &str| format!("        if not _sw_binding(n_{id}): return\n");
    match a {
        Action::Set { variable, value } => format!("        v_{variable} = e[{value}]\n"),
        Action::Transition { state } => format!("        sw_state = {}\n", quoted(state)),
        Action::Move2d {
            entity,
            velocity,
            max_speed,
        } => format!(
            "{}        n_{entity}.velocity = Vector2(e[{velocity}]).limit_length({max_speed:?})\n        n_{entity}.move_and_slide()\n",
            binding(entity)
        ),
        Action::Move3d {
            entity,
            velocity,
            max_speed,
        } => format!(
            "{}        n_{entity}.velocity = Vector3(e[{velocity}]).limit_length({max_speed:?})\n        n_{entity}.move_and_slide()\n",
            binding(entity)
        ),
        Action::Label {
            entity,
            prefix,
            variable,
        } => format!(
            "{}        n_{entity}.text = {} + str(v_{variable})\n",
            binding(entity),
            quoted(prefix)
        ),
        Action::Visible { entity, visible } => format!(
            "{}        n_{entity}.visible = {visible}\n",
            binding(entity)
        ),
        Action::Position { entity, value } => format!(
            "{}        n_{entity}.position = e[{value}]\n",
            binding(entity)
        ),
        Action::Animate { entity, clip } => format!(
            "{}        n_{entity}.play({})\n",
            binding(entity),
            quoted(clip)
        ),
        Action::PlayAudio { entity } => format!("{}        n_{entity}.play()\n", binding(entity)),
        Action::StartTimer { timer } => format!("        t_{timer}.start()\n"),
        Action::CancelTimer { timer } => format!("        t_{timer}.stop()\n"),
        Action::Emit { signal } => format!("        _sw_emit({})\n", quoted(signal)),
        Action::Spawn { scene, count } => format!(
            "        _sw_spawn(load({}) as PackedScene, {count})\n",
            quoted(&format!("res://scenes/{scene}.tscn"))
        ),
        Action::Despawn { entity } => {
            format!("{}        n_{entity}.queue_free()\n", binding(entity))
        }
        Action::Restart => String::from(
            "        get_tree().reload_current_scene.call_deferred()\n        return\n",
        ),
        Action::ChangeScene { scene } => format!(
            "        get_tree().change_scene_to_file.call_deferred({})\n        return\n",
            quoted(&format!("res://scenes/{scene}.tscn"))
        ),
    }
}
