#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct RestOperationMeta {
    pub operation_id: &'static str,
    pub capability: &'static str,
    pub method: &'static str,
    pub path: &'static str,
    pub scope: &'static str,
    pub deprecated: bool,
    pub credential: &'static str,
}

pub const REST_SPEC_SHA: &str = "04fbbc719706e986fc79f3050d3e068e118275d9";
pub const REST_OPERATIONS: &[RestOperationMeta] = &[
    RestOperationMeta {
        operation_id: "deleteComment",
        capability: "cloud.comment.delete",
        method: "DELETE",
        path: "/v1/files/{file_key}/comments/{comment_id}",
        scope: "file_comments:write",
        deprecated: false,
        credential: "oauth_or_pat",
    },
    RestOperationMeta {
        operation_id: "deleteCommentReaction",
        capability: "cloud.reaction.delete",
        method: "DELETE",
        path: "/v1/files/{file_key}/comments/{comment_id}/reactions",
        scope: "file_comments:write",
        deprecated: false,
        credential: "oauth_or_pat",
    },
    RestOperationMeta {
        operation_id: "deleteDevResource",
        capability: "cloud.dev_resource.delete",
        method: "DELETE",
        path: "/v1/files/{file_key}/dev_resources/{dev_resource_id}",
        scope: "file_dev_resources:write",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "deleteWebhook",
        capability: "cloud.webhook.delete",
        method: "DELETE",
        path: "/v2/webhooks/{webhook_id}",
        scope: "webhooks:write",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getActivityLogs",
        capability: "cloud.activity_logs.list",
        method: "GET",
        path: "/v1/activity_logs",
        scope: "org:activity_log_read",
        deprecated: false,
        credential: "oauth_only",
    },
    RestOperationMeta {
        operation_id: "getAiUsageDaily",
        capability: "cloud.ai_usage.daily",
        method: "GET",
        path: "/v1/ai_usage/daily",
        scope: "org:ai_metering_usage_read",
        deprecated: false,
        credential: "plan_only",
    },
    RestOperationMeta {
        operation_id: "getCommentReactions",
        capability: "cloud.reactions.list",
        method: "GET",
        path: "/v1/files/{file_key}/comments/{comment_id}/reactions",
        scope: "file_comments:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getComments",
        capability: "cloud.comments.list",
        method: "GET",
        path: "/v1/files/{file_key}/comments",
        scope: "file_comments:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getComponent",
        capability: "cloud.library.component.get",
        method: "GET",
        path: "/v1/components/{key}",
        scope: "library_assets:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getComponentSet",
        capability: "cloud.library.component_set.get",
        method: "GET",
        path: "/v1/component_sets/{key}",
        scope: "library_assets:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getDevResources",
        capability: "cloud.dev_resources.list",
        method: "GET",
        path: "/v1/files/{file_key}/dev_resources",
        scope: "file_dev_resources:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getDeveloperLogs",
        capability: "cloud.developer_logs.query",
        method: "POST",
        path: "/v1/developer_logs",
        scope: "org:developer_log_read",
        deprecated: false,
        credential: "plan_only",
    },
    RestOperationMeta {
        operation_id: "getFile",
        capability: "cloud.file.get",
        method: "GET",
        path: "/v1/files/{file_key}",
        scope: "file_content:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getFileComponentSets",
        capability: "cloud.file.component_sets",
        method: "GET",
        path: "/v1/files/{file_key}/component_sets",
        scope: "library_content:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getFileComponents",
        capability: "cloud.file.components",
        method: "GET",
        path: "/v1/files/{file_key}/components",
        scope: "library_content:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getFileMeta",
        capability: "cloud.file.metadata",
        method: "GET",
        path: "/v1/files/{file_key}/meta",
        scope: "file_metadata:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getFileNodes",
        capability: "cloud.file.nodes",
        method: "GET",
        path: "/v1/files/{file_key}/nodes",
        scope: "file_content:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getFileStyles",
        capability: "cloud.file.styles",
        method: "GET",
        path: "/v1/files/{file_key}/styles",
        scope: "library_content:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getFileVersions",
        capability: "cloud.versions.list",
        method: "GET",
        path: "/v1/files/{file_key}/versions",
        scope: "file_versions:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getFolderFiles",
        capability: "cloud.folder.files",
        method: "GET",
        path: "/v2/folders/{folder_id}/files",
        scope: "folders:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getFolderFolders",
        capability: "cloud.folder.subfolders",
        method: "GET",
        path: "/v2/folders/{folder_id}/folders",
        scope: "folders:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getFolderMeta",
        capability: "cloud.folder.metadata",
        method: "GET",
        path: "/v2/folders/{folder_id}/meta",
        scope: "folder_metadata:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getImageFills",
        capability: "cloud.image_fills.list",
        method: "GET",
        path: "/v1/files/{file_key}/images",
        scope: "file_content:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getImages",
        capability: "cloud.images.render",
        method: "GET",
        path: "/v1/images/{file_key}",
        scope: "file_content:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getLibraryAnalyticsComponentActions",
        capability: "cloud.library_analytics.component.actions",
        method: "GET",
        path: "/v1/analytics/libraries/{file_key}/component/actions",
        scope: "library_analytics:read",
        deprecated: false,
        credential: "oauth_pat_or_plan_enterprise",
    },
    RestOperationMeta {
        operation_id: "getLibraryAnalyticsComponentUsages",
        capability: "cloud.library_analytics.component.usages",
        method: "GET",
        path: "/v1/analytics/libraries/{file_key}/component/usages",
        scope: "library_analytics:read",
        deprecated: false,
        credential: "oauth_pat_or_plan_enterprise",
    },
    RestOperationMeta {
        operation_id: "getLibraryAnalyticsStyleActions",
        capability: "cloud.library_analytics.style.actions",
        method: "GET",
        path: "/v1/analytics/libraries/{file_key}/style/actions",
        scope: "library_analytics:read",
        deprecated: false,
        credential: "oauth_pat_or_plan_enterprise",
    },
    RestOperationMeta {
        operation_id: "getLibraryAnalyticsStyleUsages",
        capability: "cloud.library_analytics.style.usages",
        method: "GET",
        path: "/v1/analytics/libraries/{file_key}/style/usages",
        scope: "library_analytics:read",
        deprecated: false,
        credential: "oauth_pat_or_plan_enterprise",
    },
    RestOperationMeta {
        operation_id: "getLibraryAnalyticsVariableActions",
        capability: "cloud.library_analytics.variable.actions",
        method: "GET",
        path: "/v1/analytics/libraries/{file_key}/variable/actions",
        scope: "library_analytics:read",
        deprecated: false,
        credential: "oauth_pat_or_plan_enterprise",
    },
    RestOperationMeta {
        operation_id: "getLibraryAnalyticsVariableUsages",
        capability: "cloud.library_analytics.variable.usages",
        method: "GET",
        path: "/v1/analytics/libraries/{file_key}/variable/usages",
        scope: "library_analytics:read",
        deprecated: false,
        credential: "oauth_pat_or_plan_enterprise",
    },
    RestOperationMeta {
        operation_id: "getLocalVariables",
        capability: "cloud.variables.local",
        method: "GET",
        path: "/v1/files/{file_key}/variables/local",
        scope: "file_variables:read",
        deprecated: false,
        credential: "oauth_pat_or_plan_enterprise",
    },
    RestOperationMeta {
        operation_id: "getMe",
        capability: "cloud.user.current",
        method: "GET",
        path: "/v1/me",
        scope: "current_user:read",
        deprecated: false,
        credential: "oauth_or_pat",
    },
    RestOperationMeta {
        operation_id: "getOEmbed",
        capability: "cloud.oembed.get",
        method: "GET",
        path: "/v1/oembed",
        scope: "file_metadata:read",
        deprecated: false,
        credential: "oauth_or_pat",
    },
    RestOperationMeta {
        operation_id: "getPayments",
        capability: "cloud.payments.lookup",
        method: "GET",
        path: "/v1/payments",
        scope: "personal_access_token",
        deprecated: false,
        credential: "pat_only",
    },
    RestOperationMeta {
        operation_id: "getProjectFiles",
        capability: "cloud.legacy.project.files",
        method: "GET",
        path: "/v1/projects/{project_id}/files",
        scope: "projects:read",
        deprecated: true,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getProjectMeta",
        capability: "cloud.legacy.project.metadata",
        method: "GET",
        path: "/v1/projects/{project_id}/meta",
        scope: "project_metadata:read",
        deprecated: true,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getPublishedVariables",
        capability: "cloud.variables.published",
        method: "GET",
        path: "/v1/files/{file_key}/variables/published",
        scope: "file_variables:read",
        deprecated: false,
        credential: "oauth_pat_or_plan_enterprise",
    },
    RestOperationMeta {
        operation_id: "getStyle",
        capability: "cloud.library.style.get",
        method: "GET",
        path: "/v1/styles/{key}",
        scope: "library_assets:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getTeamComponentSets",
        capability: "cloud.team.component_sets",
        method: "GET",
        path: "/v1/teams/{team_id}/component_sets",
        scope: "team_library_content:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getTeamComponents",
        capability: "cloud.team.components",
        method: "GET",
        path: "/v1/teams/{team_id}/components",
        scope: "team_library_content:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getTeamFolders",
        capability: "cloud.team.folders",
        method: "GET",
        path: "/v2/teams/{team_id}/folders",
        scope: "folders:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getTeamProjects",
        capability: "cloud.legacy.team.projects",
        method: "GET",
        path: "/v1/teams/{team_id}/projects",
        scope: "projects:read",
        deprecated: true,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getTeamStyles",
        capability: "cloud.team.styles",
        method: "GET",
        path: "/v1/teams/{team_id}/styles",
        scope: "team_library_content:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getTeamWebhooks",
        capability: "cloud.legacy.team.webhooks",
        method: "GET",
        path: "/v2/teams/{team_id}/webhooks",
        scope: "webhooks:read",
        deprecated: true,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getWebhook",
        capability: "cloud.webhook.get",
        method: "GET",
        path: "/v2/webhooks/{webhook_id}",
        scope: "webhooks:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getWebhookRequests",
        capability: "cloud.webhook.requests",
        method: "GET",
        path: "/v2/webhooks/{webhook_id}/requests",
        scope: "webhooks:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "getWebhooks",
        capability: "cloud.webhooks.list",
        method: "GET",
        path: "/v2/webhooks",
        scope: "webhooks:read",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "postComment",
        capability: "cloud.comment.create",
        method: "POST",
        path: "/v1/files/{file_key}/comments",
        scope: "file_comments:write",
        deprecated: false,
        credential: "oauth_or_pat",
    },
    RestOperationMeta {
        operation_id: "postCommentReaction",
        capability: "cloud.reaction.add",
        method: "POST",
        path: "/v1/files/{file_key}/comments/{comment_id}/reactions",
        scope: "file_comments:write",
        deprecated: false,
        credential: "oauth_or_pat",
    },
    RestOperationMeta {
        operation_id: "postDevResources",
        capability: "cloud.dev_resources.create",
        method: "POST",
        path: "/v1/dev_resources",
        scope: "file_dev_resources:write",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "postVariables",
        capability: "cloud.variables.mutate",
        method: "POST",
        path: "/v1/files/{file_key}/variables",
        scope: "file_variables:write",
        deprecated: false,
        credential: "oauth_or_pat_enterprise_full_seat",
    },
    RestOperationMeta {
        operation_id: "postWebhook",
        capability: "cloud.webhook.create",
        method: "POST",
        path: "/v2/webhooks",
        scope: "webhooks:write",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "putDevResources",
        capability: "cloud.dev_resources.update",
        method: "PUT",
        path: "/v1/dev_resources",
        scope: "file_dev_resources:write",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
    RestOperationMeta {
        operation_id: "putWebhook",
        capability: "cloud.webhook.update",
        method: "PUT",
        path: "/v2/webhooks/{webhook_id}",
        scope: "webhooks:write",
        deprecated: false,
        credential: "oauth_pat_or_plan",
    },
];

pub const REST_DOCUMENTED_EXTRAS: &[RestOperationMeta] = &[RestOperationMeta {
    operation_id: "getDiscoveryTextEvents",
    capability: "cloud.discovery.text_events",
    method: "GET",
    path: "/v1/discovery",
    scope: "org:discovery_read",
    deprecated: false,
    credential: "oauth_only",
}];

pub fn metadata(capability: &str) -> Option<&'static RestOperationMeta> {
    REST_OPERATIONS
        .iter()
        .chain(REST_DOCUMENTED_EXTRAS.iter())
        .find(|entry| entry.capability == capability)
}

pub fn official_operation_ids() -> impl Iterator<Item = &'static str> {
    REST_OPERATIONS.iter().map(|entry| entry.operation_id)
}
