use super::{Op, op};
use semwright_types::{Idempotency, Risk};

pub(super) fn operations() -> Vec<Op> {
    use Idempotency::{Idempotent, NonIdempotent, ReadOnly};
    use Risk::{Destructive, MutatingReversible, ReadOnly as ReadRisk};
    vec![
        op(
            "group.create",
            "Group explicit nodes under an explicit parent",
            MutatingReversible,
            NonIdempotent,
            true,
        ),
        op(
            "group.ungroup",
            "Ungroup an explicit group-like node",
            MutatingReversible,
            NonIdempotent,
            true,
        ),
        op(
            "slice.create",
            "Create a Figma export slice",
            MutatingReversible,
            NonIdempotent,
            true,
        ),
        op(
            "page.divider.create",
            "Create a document page divider",
            MutatingReversible,
            NonIdempotent,
            true,
        ),
        op(
            "file.thumbnail.get",
            "Inspect the explicit file thumbnail node",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "file.thumbnail.set",
            "Set or clear the file thumbnail node",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "motion.playhead.get",
            "Inspect the current Motion playhead (Beta)",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "history.commit",
            "Commit the current plugin mutation group to Figma undo history",
            MutatingReversible,
            NonIdempotent,
            false,
        ),
        op(
            "history.undo",
            "Trigger Figma undo to the prior plugin checkpoint",
            Destructive,
            Idempotency::Destructive,
            false,
        ),
        op(
            "brush.load",
            "Load an available Figma stretch/scatter brush family",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "artifact.upload.begin",
            "Create a bounded in-memory artifact upload",
            MutatingReversible,
            NonIdempotent,
            false,
        ),
        op(
            "artifact.upload.append",
            "Append a bounded chunk at the exact artifact offset",
            MutatingReversible,
            Idempotent,
            false,
        ),
        op(
            "artifact.status",
            "Inspect a bounded driver artifact",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "image.create",
            "Create a Figma image resource from an uploaded artifact",
            MutatingReversible,
            NonIdempotent,
            true,
        ),
        op(
            "image.inspect",
            "Inspect a Figma image hash and dimensions",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "image.export",
            "Stage raw Figma image bytes as a bounded artifact",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "video.create",
            "Create a Figma video resource from an uploaded artifact",
            MutatingReversible,
            NonIdempotent,
            true,
        ),
        op(
            "media.fill.apply",
            "Apply an image/video hash as a node fill",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "buzz.media_content.set",
            "Set a Buzz dynamic media field",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "component.variant_matrix.create",
            "Generate a bounded component variant matrix",
            MutatingReversible,
            NonIdempotent,
            true,
        ),
        op(
            "component.size_variants.create",
            "Generate bounded component size variants",
            MutatingReversible,
            NonIdempotent,
            true,
        ),
        op(
            "node.plugin_data.get",
            "Read Semwright-namespaced plugin data",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "node.plugin_data.set",
            "Write Semwright-namespaced plugin data",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "node.relaunch_data.get",
            "Inspect Figma relaunch metadata",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "node.relaunch_data.set",
            "Replace bounded Figma relaunch metadata",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "figjam.table.inspect",
            "Inspect a FigJam table",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "figjam.table.cell.inspect",
            "Inspect a FigJam table cell",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "figjam.table.cell.text.set",
            "Set FigJam table cell text",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "figjam.table.row.insert",
            "Insert a FigJam table row",
            MutatingReversible,
            NonIdempotent,
            true,
        ),
        op(
            "figjam.table.row.remove",
            "Remove a FigJam table row",
            Destructive,
            Idempotency::Destructive,
            false,
        ),
        op(
            "figjam.table.column.insert",
            "Insert a FigJam table column",
            MutatingReversible,
            NonIdempotent,
            true,
        ),
        op(
            "figjam.table.column.remove",
            "Remove a FigJam table column",
            Destructive,
            Idempotency::Destructive,
            false,
        ),
        op(
            "figjam.table.row.move",
            "Move a FigJam table row",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "figjam.table.column.move",
            "Move a FigJam table column",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "figjam.table.row.resize",
            "Resize a FigJam table row",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "figjam.table.column.resize",
            "Resize a FigJam table column",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "node.bindings.inspect",
            "Inspect variable and component-property bindings",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "node.properties.patch",
            "Patch an allowlisted semantic node-property set",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "canvas.info",
            "Inspect current canvas, children and selection",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "canvas.next_position",
            "Compute a non-overlapping canvas placement hint",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "canvas.arrange",
            "Arrange explicit nodes into a bounded grid",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "slot.list",
            "List slots under a component/component-set/instance",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "slot.preferred.set",
            "Set preferred component values for a slot property",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "slot.content.add",
            "Add bounded semantic content to a slot",
            MutatingReversible,
            NonIdempotent,
            true,
        ),
        op(
            "analysis.colors",
            "Analyze bounded color usage",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "analysis.typography",
            "Analyze bounded typography usage",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "analysis.spacing",
            "Analyze bounded spacing and radius usage",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "analysis.clusters",
            "Find repeated geometry/layout clusters",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "validate.lint",
            "Run deterministic Figma document lint rules",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "font.status",
            "Report whether the document has missing fonts",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "viewport.canvas_view.get",
            "Inspect the Slides/Buzz canvas view mode",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "viewport.canvas_view.set",
            "Set the Slides/Buzz canvas view mode",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "library.collection.extend",
            "Create an extended variable collection from a library collection",
            MutatingReversible,
            NonIdempotent,
            true,
        ),
        op(
            "variable.bind.paint",
            "Bind or clear a variable on an indexed solid paint",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "variable.bind.effect",
            "Bind or clear a variable on an indexed effect",
            MutatingReversible,
            Idempotent,
            true,
        ),
        op(
            "variable.bind.layout_grid",
            "Bind or clear a variable on an indexed layout grid",
            MutatingReversible,
            Idempotent,
            true,
        ),
    ]
}
