use super::{Op, op};
use semwright_types::{Idempotency, Risk};

pub(super) fn operations() -> Vec<Op> {
    use Idempotency::{Destructive as DestructiveIdem, Idempotent, NonIdempotent, ReadOnly};
    use Risk::{
        Destructive, MutatingReversible, PrivilegeSensitive, ReadOnly as ReadRisk, SecretAccess,
    };
    vec![
        op(
            "cloud.status",
            "Inspect whether the optional Figma REST credential transport is configured",
            ReadRisk,
            ReadOnly,
            true,
        ),
        op(
            "cloud.discovery.text_events",
            "Read up to 24 hours of organization text-event download links from the official Discovery API",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.comment.delete",
            "Call official Figma REST operation deleteComment (file_comments:write)",
            Destructive,
            DestructiveIdem,
            false,
        ),
        op(
            "cloud.reaction.delete",
            "Call official Figma REST operation deleteCommentReaction (file_comments:write)",
            Destructive,
            DestructiveIdem,
            false,
        ),
        op(
            "cloud.dev_resource.delete",
            "Call official Figma REST operation deleteDevResource (file_dev_resources:write)",
            Destructive,
            DestructiveIdem,
            false,
        ),
        op(
            "cloud.webhook.delete",
            "Call official Figma REST operation deleteWebhook (webhooks:write)",
            Destructive,
            DestructiveIdem,
            false,
        ),
        op(
            "cloud.activity_logs.list",
            "Call official Figma REST operation getActivityLogs (org:activity_log_read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.ai_usage.daily",
            "Read daily Figma AI usage metering (Enterprise plan token required)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.reactions.list",
            "Call official Figma REST operation getCommentReactions (file_comments:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.comments.list",
            "Call official Figma REST operation getComments (file_comments:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.library.component.get",
            "Call official Figma REST operation getComponent (library_assets:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.library.component_set.get",
            "Call official Figma REST operation getComponentSet (library_assets:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.dev_resources.list",
            "Call official Figma REST operation getDevResources (file_dev_resources:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.developer_logs.query",
            "Query bounded developer access logs (Enterprise plan token required)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.file.get",
            "Read a bounded Figma file document through the official REST API",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.file.component_sets",
            "Call official Figma REST operation getFileComponentSets (library_content:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.file.components",
            "Call official Figma REST operation getFileComponents (library_content:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.file.metadata",
            "Call official Figma REST operation getFileMeta (file_metadata:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.file.nodes",
            "Read explicit nodes from a Figma file through the official REST API",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.file.styles",
            "Call official Figma REST operation getFileStyles (library_content:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.versions.list",
            "Call official Figma REST operation getFileVersions (file_versions:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.folder.files",
            "Call official Figma REST operation getFolderFiles (folders:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.folder.subfolders",
            "Call official Figma REST operation getFolderFolders (folders:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.folder.metadata",
            "Call official Figma REST operation getFolderMeta (folder_metadata:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.image_fills.list",
            "Call official Figma REST operation getImageFills (file_content:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.images.render",
            "Request Figma render URLs for explicit node IDs",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.library_analytics.component.actions",
            "Call official Figma REST operation getLibraryAnalyticsComponentActions (library_analytics:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.library_analytics.component.usages",
            "Call official Figma REST operation getLibraryAnalyticsComponentUsages (library_analytics:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.library_analytics.style.actions",
            "Call official Figma REST operation getLibraryAnalyticsStyleActions (library_analytics:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.library_analytics.style.usages",
            "Call official Figma REST operation getLibraryAnalyticsStyleUsages (library_analytics:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.library_analytics.variable.actions",
            "Call official Figma REST operation getLibraryAnalyticsVariableActions (library_analytics:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.library_analytics.variable.usages",
            "Call official Figma REST operation getLibraryAnalyticsVariableUsages (library_analytics:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.variables.local",
            "Call official Figma REST operation getLocalVariables (file_variables:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.user.current",
            "Call official Figma REST operation getMe (current_user:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.oembed.get",
            "Call official Figma REST operation getOEmbed (file_metadata:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.payments.lookup",
            "Call official Figma REST operation getPayments (personal_access_token)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.legacy.project.files",
            "Call official Figma REST operation getProjectFiles (projects:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.legacy.project.metadata",
            "Call official Figma REST operation getProjectMeta (project_metadata:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.variables.published",
            "Call official Figma REST operation getPublishedVariables (file_variables:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.library.style.get",
            "Call official Figma REST operation getStyle (library_assets:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.team.component_sets",
            "Call official Figma REST operation getTeamComponentSets (team_library_content:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.team.components",
            "Call official Figma REST operation getTeamComponents (team_library_content:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.team.folders",
            "Call official Figma REST operation getTeamFolders (folders:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.legacy.team.projects",
            "Call official Figma REST operation getTeamProjects (projects:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.team.styles",
            "Call official Figma REST operation getTeamStyles (team_library_content:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.legacy.team.webhooks",
            "Call official Figma REST operation getTeamWebhooks (webhooks:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.webhook.get",
            "Call official Figma REST operation getWebhook (webhooks:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.webhook.requests",
            "Call official Figma REST operation getWebhookRequests (webhooks:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.webhooks.list",
            "Call official Figma REST operation getWebhooks (webhooks:read)",
            SecretAccess,
            ReadOnly,
            false,
        ),
        op(
            "cloud.comment.create",
            "Call official Figma REST operation postComment (file_comments:write)",
            MutatingReversible,
            NonIdempotent,
            false,
        ),
        op(
            "cloud.reaction.add",
            "Call official Figma REST operation postCommentReaction (file_comments:write)",
            MutatingReversible,
            NonIdempotent,
            false,
        ),
        op(
            "cloud.dev_resources.create",
            "Call official Figma REST operation postDevResources (file_dev_resources:write)",
            PrivilegeSensitive,
            NonIdempotent,
            false,
        ),
        op(
            "cloud.variables.mutate",
            "Apply explicit REST variable changes (Enterprise Full seat required)",
            PrivilegeSensitive,
            NonIdempotent,
            false,
        ),
        op(
            "cloud.webhook.create",
            "Call official Figma REST operation postWebhook (webhooks:write)",
            PrivilegeSensitive,
            NonIdempotent,
            false,
        ),
        op(
            "cloud.dev_resources.update",
            "Call official Figma REST operation putDevResources (file_dev_resources:write)",
            PrivilegeSensitive,
            Idempotent,
            false,
        ),
        op(
            "cloud.webhook.update",
            "Call official Figma REST operation putWebhook (webhooks:write)",
            PrivilegeSensitive,
            Idempotent,
            false,
        ),
    ]
}
