use super::{model::*, validate};
use semwright_semantic_composition::{Digest, Result, canonical_digest, ensure};
use serde::Serialize;
use std::collections::BTreeMap;
mod behavior;
mod scene;
#[derive(Debug, Clone, Serialize)]
pub struct GeneratedFile {
    pub logical_id: String,
    pub kind: String,
    pub sha256: Digest,
}
#[derive(Debug, Clone)]
pub struct CompiledProject {
    pub intent_digest: Digest,
    pub files: BTreeMap<String, String>,
    pub provenance: BTreeMap<String, GeneratedFile>,
}
pub(crate) fn quoted(text: &str) -> String {
    // JSON quoted string escapes preserve Unicode and cannot terminate a source literal.
    serde_json::to_string(text).expect("serializing a Rust string cannot fail")
}
pub(crate) fn vector(name: &str, values: &[f64]) -> String {
    format!(
        "{}({})",
        name,
        values
            .iter()
            .map(|n| if *n == 0.0 {
                "0.0".into()
            } else {
                format!("{n:?}")
            })
            .collect::<Vec<_>>()
            .join(", ")
    )
}
pub(crate) fn value(v: &Literal) -> String {
    match v {
        Literal::Bool(v) => v.to_string(),
        Literal::Int(v) => v.to_string(),
        Literal::Scalar(v) => format!("{v:?}"),
        Literal::Vector2(v) => vector("Vector2", v),
        Literal::Vector3(v) => vector("Vector3", v),
        Literal::Color(v) => vector("Color", v),
    }
}
fn insert(
    out: &mut CompiledProject,
    path: String,
    text: String,
    logical: String,
    kind: &str,
) -> Result<()> {
    ensure(text.len() <= 1_048_576, "generated file budget")?;
    ensure(
        out.files.len() < 256 && !out.files.contains_key(&path),
        "generated file collision/count",
    )?;
    out.provenance.insert(
        path.clone(),
        GeneratedFile {
            logical_id: logical,
            kind: kind.into(),
            sha256: Digest::of_bytes(text.as_bytes()),
        },
    );
    out.files.insert(path, text);
    Ok(())
}
pub fn compile(spec: &GodotAuthoringSpec) -> Result<CompiledProject> {
    validate(spec)?;
    let mut out = CompiledProject {
        intent_digest: canonical_digest(spec)?,
        files: BTreeMap::new(),
        provenance: BTreeMap::new(),
    };
    let mut project = format!(
        "; Generated by {GENERATOR_VERSION}.\nconfig_version=5\n\n[application]\nconfig/name={}\nrun/main_scene={}\nconfig/features=PackedStringArray(\"4.7\", \"GL Compatibility\")\n\n[display]\nwindow/size/viewport_width={}\nwindow/size/viewport_height={}\n\n[physics]\ncommon/physics_ticks_per_second={}\n\n[rendering]\nrenderer/rendering_method=\"gl_compatibility\"\nrenderer/rendering_method.mobile=\"gl_compatibility\"\n\n[input]\n",
        quoted(&spec.title),
        quoted(&format!("res://scenes/{}.tscn", spec.main_scene)),
        spec.settings.width,
        spec.settings.height,
        spec.settings.physics_ticks
    );
    for input in &spec.inputs {
        project.push_str(&format!("\n{}={{\n\"deadzone\": 0.2,\n\"events\": [Object(InputEventKey,\"physical_keycode\":{})]\n}}\n",input.id,input.key.code()));
    }
    insert(
        &mut out,
        "project.godot".into(),
        project,
        spec.project.clone(),
        "project",
    )?;
    let preset = "[preset.0]\nname=\"Linux\"\nplatform=\"Linux\"\nrunnable=true\nexport_filter=\"all_resources\"\ninclude_filter=\"\"\nexclude_filter=\"addons/*,*.semwright.json,*.source-map.json,authoring-spec.json\"\nexport_path=\"\"\nscript_export_mode=0\n\n[preset.0.options]\nbinary_format/architecture=\"x86_64\"\nbinary_format/embed_pck=true\n";
    insert(
        &mut out,
        "export_presets.cfg".into(),
        preset.into(),
        spec.project.clone(),
        "export_config",
    )?;
    insert(
        &mut out,
        "scripts/_sw_runtime.gd".into(),
        include_str!("compiler/runtime.gd").into(),
        spec.project.clone(),
        "runtime",
    )?;
    for s in &spec.scenes {
        scene::generate(spec, s, &mut out)?;
        let (script, map) = behavior::generate(spec, s)?;
        insert(
            &mut out,
            format!("scripts/{}.gd", s.id),
            script,
            s.id.clone(),
            "behavior",
        )?;
        insert(
            &mut out,
            format!("scripts/{}.source-map.json", s.id),
            map,
            s.id.clone(),
            "source_map",
        )?;
    }
    ensure(
        out.files.values().map(String::len).sum::<usize>() <= 4 * 1_048_576,
        "compiled project byte budget",
    )?;
    Ok(out)
}
