import {describe,it,expect} from "vitest";
import fs from "node:fs";
import path from "node:path";
const sourceDir=path.join(process.cwd(),"src");
const sourceFiles=fs.readdirSync(sourceDir).filter(name=>name.endsWith(".ts")).sort();
const allCode=sourceFiles.map(name=>fs.readFileSync(path.join(sourceDir,name),"utf8")).join("\n");
const code=fs.readFileSync(path.join(sourceDir,"code.ts"),"utf8");
const ui=fs.readFileSync(path.join(sourceDir,"ui.html"),"utf8");
const manifest=JSON.parse(fs.readFileSync(path.join(process.cwd(),"manifest.json"),"utf8"));
const devInspect=JSON.parse(fs.readFileSync(path.join(process.cwd(),"manifest.dev-inspect.json"),"utf8"));
const devCodegen=JSON.parse(fs.readFileSync(path.join(process.cwd(),"manifest.dev-codegen.json"),"utf8"));
const textReview=JSON.parse(fs.readFileSync(path.join(process.cwd(),"manifest.textreview.json"),"utf8"));
const collaboration=JSON.parse(fs.readFileSync(path.join(process.cwd(),"manifest.collaboration.json"),"utf8"));
const coverage=JSON.parse(fs.readFileSync(path.join(process.cwd(),"../docs/API_COVERAGE.json"),"utf8"));
const generatedSurface=fs.readFileSync(path.join(sourceDir,"generated_api_surface.ts"),"utf8");
describe("security surface",()=>{
 it("has no eval or Function constructor",()=>{expect(allCode).not.toMatch(/\beval\s*\(/);expect(allCode).not.toMatch(/new\s+Function/);});
 it("uses dynamic page access",()=>expect(manifest.documentAccess).toBe("dynamic-page"));
 it("does not allow wildcard network",()=>expect(manifest.networkAccess.allowedDomains).toEqual(["none"]));
 it("limits dev websocket to loopback",()=>expect(manifest.networkAccess.devAllowedDomains).toEqual(["ws://127.0.0.1:38471"]));
 it("uses async node lookup",()=>expect(code).toContain("getNodeByIdAsync"));
 it("uses async page switching",()=>expect(code).toContain("setCurrentPageAsync"));
 it("loads fonts before text mutation",()=>expect(code).toContain("loadFontAsync"));
 it("uses setReactionsAsync",()=>expect(code).toContain("setReactionsAsync"));
 it("sanitizes SVG",()=>expect(code).toContain("rejectUnsafeSvg"));
 it("bounds tree traversal",()=>expect(code).toContain("MAX_TREE"));
 it("keeps normal editors separate from Dev Mode",()=>{expect(manifest.editorType).toEqual(["figma","figjam","slides","buzz"]);expect(manifest.editorType).not.toContain("dev");});
 it("ships an inspect-only Dev Mode manifest",()=>{expect(devInspect.editorType).toEqual(["dev"]);expect(devInspect.capabilities).toEqual(["inspect","vscode"]);});
 it("ships a dedicated codegen Dev Mode manifest",()=>{expect(devCodegen.editorType).toEqual(["dev"]);expect(devCodegen.capabilities).toEqual(["codegen","vscode"]);expect(devCodegen.codegenLanguages.length).toBeGreaterThan(0);});
 it("ships a dedicated text-review manifest",()=>{expect(textReview.editorType).toEqual(["figma","figjam"]);expect(textReview.capabilities).toEqual(["textreview"]);expect(textReview.permissions).toBeUndefined();});
 it("keeps collaboration permissions out of the default manifest",()=>{expect(manifest.permissions).toEqual(["teamlibrary"]);expect(collaboration.permissions).toEqual(["teamlibrary","currentuser","activeusers","fileusers"]);});
 it("keeps every manifest offline except the loopback development bridge",()=>{for(const m of [manifest,collaboration,devInspect,devCodegen,textReview]){expect(m.networkAccess.allowedDomains).toEqual(["none"]);expect(m.networkAccess.devAllowedDomains).toEqual(["ws://127.0.0.1:38471"]);}});
});
describe("advanced API",()=>{
 it("implements Motion style operations",()=>expect(code).toContain("applyAnimationStyle"));
 it("implements manual keyframes",()=>expect(code).toContain("applyManualKeyframeTrack"));
 it("implements timeline duration",()=>expect(code).toContain("setTimelineDuration"));
 it("implements spring normalization",()=>expect(code).toContain("physicalSpringToNormalized"));
 it("implements FigJam connectors",()=>expect(code).toContain("createConnector"));
 it("implements variables",()=>expect(code).toContain("getLocalVariablesAsync"));
 it("keeps the pinned SceneNode surface exhaustively classified",()=>{expect(coverage.summary.scene_node_members).toBeGreaterThan(3000);expect(coverage.summary.supported_scene_node_members).toBe(coverage.summary.scene_node_members);expect(coverage.summary.unmapped_method_names).toEqual([]);});
 it("keeps auxiliary public methods exhaustively classified",()=>{expect(coverage.summary.auxiliary_method_entries).toBeGreaterThan(40);expect(coverage.summary.unclassified_auxiliary_methods).toBe(0);});
 it("generates auxiliary property allowlists from typings",()=>{for(const kind of ["STYLE","VARIABLE","COLLECTION"]){expect(coverage.auxiliary_property_surface[kind].readable.length).toBeGreaterThan(0);}expect(generatedSurface).toContain("SEMWRIGHT_FIGMA_AUX_READ_PROPERTIES");expect(generatedSurface).toContain("SEMWRIGHT_FIGMA_AUX_WRITE_PROPERTIES");});
 it("covers privileged auxiliary APIs without eval",()=>{expect(allCode).toContain("addMeasurement");expect(allCode).toContain("valuesByModeForCollectionAsync");expect(allCode).toContain("getStyleConsumersAsync");});
});
describe("authenticated loopback bridge",()=>{
 it("never sends the pairing secret as protocol data",()=>expect(ui).not.toContain("pairing_secret"));
 it("uses WebCrypto HMAC SHA-256",()=>{expect(ui).toContain("crypto.subtle.importKey");expect(ui).toContain('name:"HMAC"');});
 it("waits for a server-generated challenge",()=>{expect(ui).toContain('type:"hello",protocol:2');expect(ui).toContain('m.type==="challenge"');});
 it("authenticates the server challenge with a separate HMAC proof",()=>{expect(ui).toContain('type:"authenticate"');expect(ui).toContain("proof:authProof");expect(ui).toContain("m.nonce");});
 it("only opens a loopback websocket",()=>expect(ui).toContain('ws://127.0.0.1:'));
});
