[package]
name = "semwright-platform-services"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
serde_json.workspace = true
semwright-platform-api = { path = "../platform-api", version = "=0.9.0-dev.1" }
semwright-types.workspace = true
libc.workspace = true
tokio.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
semwright-platform-linux-sys = { path = "../platform-linux-sys", version = "=0.9.0-dev.1" }
[target.'cfg(target_os = "macos")'.dependencies]
semwright-platform-macos-sys = { path = "../platform-macos-sys", version = "=0.9.0-dev.1" }
